LibreriaSofttek/Controllers/AutorController.cs
using LibreriaSofttek.DTOs;
using LibreriaSofttek.Exceptions;
using LibreriaSofttek.Helpers.Messages;
using LibreriaSofttek.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibreriaSofttek.Controllers
{
    public class AutorController : Controller
    {
        private readonly IAutorService _autorService;

        public AutorController(IAutorService autorService)
        {
            _autorService = autorService;
        }

        public ActionResult Index()
        {
            var autores = _autorService.GetAll();
            return View(autores);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(AutorDTO autorDTO)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _autorService.Create(autorDTO);
                    TempData["SuccessMessage"] = DefaultMessages.RegistroExitoso;
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    TempData["ErrorMessage"] = DefaultMessages.ErrorOperacion;
                }
            }

            return View(autorDTO);
        }

        public ActionResult Detail(long id)
        {
            var autor = _autorService.GetByIdDetail(id);

            if (autor == null)
                return HttpNotFound();

            return View(autor);
        }

        public ActionResult Update(long id)
        {
            var autor = _autorService.GetById(id);
            if (autor == null)
                return HttpNotFound();

            return View(autor);
        }

        [HttpPost]
        public ActionResult Update(AutorDTO autorDTO)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _autorService.Update(autorDTO);
                    TempData["SuccessMessage"] = DefaultMessages.ActualizacionExitosa;
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    TempData["ErrorMessage"] = DefaultMessages.ErrorOperacion;
                }
            }

            return View(autorDTO);
        }

        public ActionResult Delete(long id)
        {
            try
            {
                _autorService.Delete(id);
                TempData["SuccessMessage"] = DefaultMessages.EliminacionExitosa;
            }
            catch (LibroExistenteException ex)
            {
                TempData["ErrorMessage"] = ex.Message;
            }
            catch (Exception)
            {
                TempData["ErrorMessage"] = DefaultMessages.ErrorOperacion;
            }

            return RedirectToAction("Index");
        }
    }
}

LibreriaSofttek/Controllers/LibroController.cs
using LibreriaSofttek.DTOs;
using LibreriaSofttek.Exceptions;
using LibreriaSofttek.Helpers;
using LibreriaSofttek.Helpers.Messages;
using LibreriaSofttek.Interfaces;
using LibreriaSofttek.Models;
using LibreriaSofttek.Models.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibreriaSofttek.Controllers
{
    public class LibroController : Controller
    {
        private readonly ILibroService _libroService;
        private readonly IAutorService _autorService;

        public LibroController(ILibroService libroService, IAutorService autorService)
        {
            _libroService = libroService;
            _autorService = autorService;
        }

        public ActionResult Index()
        {
            var libros = _libroService.GetAll();
            return View(libros);
        }

        public ActionResult Detail(long id)
        {
            var libro = _libroService.GetByIdDetail(id);

            if (libro == null)
            {
                TempData["ErrorMessage"] = DefaultMessages.RegistroNoExiste;
                return RedirectToAction("Index");
            }

            return View(libro);
        }

        private void GetSelectList()
        {
            ViewBag.Autores = new SelectList(_autorService.GetAll(), "Id", "NombreCompleto");
            ViewBag.Anos = Enumerable.Range(1900, DateTime.Now.Year - 1899).Reverse();
            ViewBag.Generos = Enum.GetValues(typeof(GeneroEnum))
                .Cast<GeneroEnum>()
                .Select(g => new SelectListItem
                {
                    Value = ((int)g).ToString(),
                    Text = g.GetDisplayName()
                })
                .OrderBy(item => item.Text)
                .ToList();
        }

        public ActionResult Create()
        {
            GetSelectList();
            return View();
        }

        [HttpPost]
        public ActionResult Create(LibroDTO libroDTO)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _libroService.Create(libroDTO);
                    TempData["SuccessMessage"] = DefaultMessages.RegistroExitoso;
                    return RedirectToAction("Index");
                }
                catch (MaxLibrosPermitidosException ex)
                {
                    TempData["ErrorMessage"] = ex.Message;
                    return RedirectToAction("Index");
                }
                // Opción de excepción que controla el ingreso manual del IdAutor 
                catch (AutorNoExistenteExecption ex)
                {
                    TempData["ErrorMessage"] = ex.Message;
                }
                catch (Exception)
                {
                    TempData["ErrorMessage"] = DefaultMessages.ErrorOperacion;
                }
            }

            GetSelectList();
            return View(libroDTO);
        }

        public ActionResult Update(long id)
        {
            var libro = _libroService.GetById(id);
            if (libro == null)
            {
                TempData["ErrorMessage"] = DefaultMessages.RegistroNoExiste;
                return RedirectToAction("Index");
            }

            GetSelectList();
            return View(libro);
        }

        [HttpPost]
        public ActionResult Update(LibroDTO libroDTO)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _libroService.Update(libroDTO);
                    TempData["SuccessMessage"] = DefaultMessages.ActualizacionExitosa;
                    return RedirectToAction("Index");
                }
                // Opción de excepción que controla el ingreso manual del IdAutor 
                catch (AutorNoExistenteExecption ex)
                {
                    TempData["ErrorMessage"] = ex.Message;
                }
                catch (Exception)
                {
                    TempData["ErrorMessage"] = DefaultMessages.ErrorOperacion;
                }
            }

            GetSelectList();
            return View(libroDTO);
        }

        public ActionResult Delete(long id)
        {
            try
            {
                _libroService.Delete(id);
                TempData["SuccessMessage"] = DefaultMessages.EliminacionExitosa;
            }
            catch (Exception)
            {
                TempData["ErrorMessage"] = DefaultMessages.ErrorOperacion;
            }

            return RedirectToAction("Index");
        }
    }
}

LibreriaSofttek/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LibreriaSofttek</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/custom.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("LibreriaSofttek", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Libros", "Index", "Libro", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Autores", "Index", "Autor", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - <strong>LibreriaSofttek</strong> por Ana Ovalle</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")    
    @RenderSection("scripts", required: false)
</body>
</html>

<script>
    $(document).ready(function () {
        var successMessage = '@TempData["SuccessMessage"]';
        var errorMessage = '@TempData["ErrorMessage"]';

        toastr.options = {
            "closeButton": true,
            "progressBar": true,
            "positionClass": "toast-top-right",
            "timeOut": "5000"
        };

        if (successMessage && successMessage !== '') {
            toastr.success(successMessage);
        }

        if (errorMessage && errorMessage !== '') {
            toastr.error(errorMessage);
        }
    });
</script>